(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration').service('Categories', function($http, $q) {

        var factory = {};
        
        factory.fetchCategories = function (query) {
            var urlCategories = 'http://77.81.178.198:25001/onlineShop/categories?page=' + (query.page - 1) + '&size=' + query.limit;
            return $http.get(urlCategories);
        };

        factory.fetchCategory = function (id) {
            var urlCategory = 'http://77.81.178.198:25001/onlineShop/categories/' + id;
            return $http.get(urlCategory);
        };

        return factory;

    });

})();
