(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration').service('Categories', function($http, $q, $state, Config) {

        var factory = {};
        
        factory.fetchCategories = function (query) {
            var urlCategories = Config + 'categories?page=' + (query.page - 1) + '&size=' + query.limit;
            return $http.get(urlCategories);
        };

        factory.fetchCategory = function (id) {
            var urlCategory = Config + 'categories/' + id;
            return $http.get(urlCategory);
        };

        factory.deleteCategory = function (id) {
            var urlDelCategory = Config + 'categories/' + id;
            return $http.delete(urlDelCategory);
        };

        factory.addCategory = function (formData) {
            var addCategoryUrl;

            if ($state.params.id) {
                addCategoryUrl = Config + 'categories/' + $state.params.id;
                return $http.put(addCategoryUrl,formData);
            } else {
                addCategoryUrl = Config + 'categories';
                return $http.post(addCategoryUrl,formData);
            }

        };

        return factory;

    });

})();
