(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration').service('categoriesService', function($http, $q ,$injector) {

        var factory = {},
            Categories = $injector.get('Categories'),
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            },
            category = {
                loaded: false,
                fetching: true,
                data: {}
            },
            query = {
                order: 'name',
                limit: 10,
                page: 1
            };

        var successCallback = function (success) {
            console.log(success.data);
            categories.data = success.data;
            category.data = success.data;
        };

        var errorCallback = function (error) {
            console.log(error);
        };
        
        factory.getCategories = function () {
            return categories.data.content;
        };

        factory.getCategory = function () {
            return category.data;
        };

        factory.getTotalElements = function () {
            return categories.data.totalElements;
        };

        factory.getTotalPages = function () {
            return categories.data.totalPages;
        };

        factory.pagination = function (query) {
            if (query !== undefined) {
                categories.fetching = true;
                Categories.fetchCategories(query).then(successCallback,errorCallback);
            }

        };

        factory.fetchCategories = function () {
            categories.fetching = true;
            Categories.fetchCategories(query).then(successCallback,errorCallback);
        };

        factory.fetchCategory = function (id) {
            category.fetching = true;
            Categories.fetchCategory(id).then(successCallback,errorCallback);
        };

        factory.init = function (newMode) {
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            };
            category = {
                loaded: false,
                fetching: true,
                data: {}
            };
            query = {
                order: 'name',
                limit: 5,
                page: 1
            };
        };
        
        return factory;

    });

})();
