(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration').controller('categoriesController', 
    function($scope, $http, $mdDialog, $controller, categoriesService, $state) {

        categoriesService.fetchCategories();
        $scope.cb = {
            getCategories       : categoriesService.getCategories,
            getTotalElements    : categoriesService.getTotalElements,
            getTotalPages       : categoriesService.getTotalPages,
            delCategory         : categoriesService.delCategory,
            editCategory        : categoriesService.editCategory
        };
        
        $scope.selected = [];

        $scope.query = {
            limit: 10,
            page: 1
        };

        $scope.getPage = function () {
            categoriesService.pagination($scope.query);
        };

    });

})();
