(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration').controller('categoriesCtrl', function($scope,$http) {

        //TODO: Implement your controller logic here

        var get = function () {
            var url = 'http://77.81.178.198:25001/onlineShop/categories';
                $http({
                  method: 'GET',
                  url: url
                }).then(function successCallback(response) {
                    $scope.desserts = response.data;
                    console.log($scope.desserts);
                  }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.
                  });
        };

        get();

          $scope.selected = [];

  $scope.query = {
    order: 'name',
    limit: 5,
    page: 1
  };

  function success(desserts) {
    $scope.desserts = desserts;
  }

  $scope.getDesserts = function () {
    $scope.promise = $nutrition.desserts.get($scope.query, success).$promise;
  };



        // $scope.query = {
        //     order: 'name',
        //     limit: 5,
        //     page: 1
        // };

        // var errorCallback =  function (error) {
			  //     console.log(error);
        // };

        // var successCallback =  function (response) {
        //   	$scope.desserts = response.data.content;
        //   	$scope.desserts.totalElements = response.data.length;
        //   	$scope.desserts.totalPages = response.data.totalPages;
        //   	console.log('$scope.desserts',$scope.desserts);
        // };

        // var get = function () {
        //     var url = 'http://77.81.178.198:25001/onlineShop/categories?page=' + ($scope.query.page - 1) + '&size=' + $scope.query.limit;
			  //     $http.get(url).then(successCallback,errorCallback);
        // };
        // get();
        
        // $scope.selected = [];

        // function success(desserts) {
        //   //$scope.desserts = desserts;
        // }

        // $scope.getDesserts = function () {
        //   // $scope.promise = $nutrition.desserts.get($scope.query, success).$promise;
        //   	get();
        // };

    });

})();
