(function () {
	'use strict';

/**
 * This is a sample controller
 * Generated by ng-appgen Yeomen/Angular generator.
 *
 * @author: Tapas Jena
 * @copyright: Anitech Consulting Services Pvt Ltd.
 */
angular.module('administration')
	.controller('dashCtrl', function ($scope, $timeout, $mdSidenav, $state, $location) {
		
		$scope.state = $state;
		
		function buildToggler(componentId) {
			return function () {
				$mdSidenav(componentId).toggle();
			};
		}
		
		$scope.toggleLeft = buildToggler('left');
		$scope.toggleRight = buildToggler('right');


		// $scope.isActive = funccd..tion (viewLocation) { 
		// 	// console.log('$location.path()',$location.path());
		// 	// return viewLocation === $location.path();
		// 	var navLocation = viewLocation.current.ncyBreadcrumbLink;
		// 	var location = navLocation.slice(1); 
		// 	if (location === $location.path()) {
		// 		console.log('$location.path()',$location.path());
		// 	}
		// };

	});

})();
