(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration')
    .controller('FileManagerController', function($scope, $mdDialog, $http, fileManagerService) {
        
        fileManagerService.fetchFiles();
        $scope.cb = {
            getFiles        : fileManagerService.getFiles,
            loadFolder      : fileManagerService.loadFolder,
            parentDirectory : fileManagerService.parentDirectory,
            delete          : fileManagerService.delete,
            upload          : fileManagerService.upload
        };

        $scope.$watch('files.length',function(newVal,oldVal){
            console.log($scope.files);
        });
        

        // var url = 'http://77.81.178.198:25001/onlineShop/fileManager/rootDirectory',
        //     urlNavigate = 'http://77.81.178.198:25001/onlineShop/fileManager/navigateThroughFolder',
        //     urlParent = 'http://77.81.178.198:25001/onlineShop/fileManager/parentDirectory',
        //     urlDelete = 'http://77.81.178.198:25001/onlineShop/fileManager/deleteDirectory',
        //     urlRefresh = 'http://77.81.178.198:25001/onlineShop/fileManager/refreshDirectory';


        // var successCallback =  function (success) {
        //   	$scope.files = success.data.files;
        //   	$scope.thePath = success.data;
        //     console.log('successCallback',success);

        // };

        // var errorCallback =  function (error) {
		// 	console.log(error);
        // };

        // var successNavigate =  function (success) {
        //   	console.log('successNavigate',success);
        //     $scope.files = success.data.files;
        //     $scope.thePath = success.data;
        // };

        // var errorNavigate =  function (error) {
		// 	console.log('errorNavigate',error);
        // };

        // var successDelete =  function (success) {
        //   	refresh();
        // };

        // var errorDelete =  function (error) {
		// 	console.log('errorDelete',error);
        // };
        
        // var get = function () {
		// 	$http.get(url).then(successCallback,errorCallback);
        // };

        // get();

        // var navigateFolders = function () {
        //     var data = {
        //         'fileName': $scope.theFile.name,
        //         'path' : $scope.thePath.path
        //     };
        //     $http.post(urlNavigate,data).then(successNavigate,errorNavigate)
        // }; 

        // var refresh = function () {
        //     var data = {
        //         path: $scope.thePath.path
        //     }
        //     $http.post(urlRefresh,data).then(successCallback,errorCallback);
        // };

        // $scope.loadFolder = function (file) {
        //     $scope.theFile = file;
        //     if (file.folder === true) {
        //         navigateFolders();
        //     }
        // };

        // $scope.parentDirectory = function () {
        //     if ($scope.thePath.root === false) {
        //         var data = {
        //             'path' : $scope.thePath.path
        //         };
        //         $http.post(urlParent,data).then(successNavigate,errorNavigate)
        //     }
        // };

        // $scope.save = function() {
        //     $mdDialog.hide();
        // };
        // $scope.cancel = function() {
        //     $mdDialog.cancel();
        // };

        // $scope.delete = function(formData) {
        //     console.log($scope.formData.checked[0]);
        //     var files = [];
        //     _.forEach($scope.formData.checked, function(each,index){
        //         if (each === true ) {
        //             files.push({
        //                 fileName: $scope.files[index].name
        //             });
        //         }
        //     });

        //     var data = {
        //       path: $scope.thePath.path
        //     };
        //     data.files = files;
        //     $http.post(urlDelete,data).then(successDelete,errorDelete);
            
        // };

        // $scope.formData = {};
        // $scope.formData.checked = false;

})

.directive('ngRightClick', function($parse) {
    return function(scope, element, attrs) {
        var fn = $parse(attrs.ngRightClick);
        element.bind('contextmenu', function(event) {
            scope.$apply(function() {
                event.preventDefault();
                fn(scope, {$event:event});
            });
        });
    };
});

})();
