(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration')
    .controller('FileManagerController', function($scope, $mdDialog, $http) {
        
        // fileManagerService.fetchFiles();
        // $scope.cb = {
        //     getFiles : fileManagerService.getFiles
        // };

        var url = 'http://77.81.178.198:25001/onlineShop/fileManager/rootDirectory',
            urlNavigate = 'http://77.81.178.198:25001/onlineShop/fileManager/navigateThroughFolder',
            urlParent = 'http://77.81.178.198:25001/onlineShop/fileManager/parentDirectory';


        var successCallback =  function (success) {
          	$scope.files = success.data.files;
          	$scope.thePath = success.data;
        };

        var errorCallback =  function (error) {
			console.log(error);
        };

        var successNavigate =  function (success) {
          	console.log('successNavigate',success);
            $scope.files = success.data.files;
            $scope.thePath = success.data;
        };

        var errorNavigate =  function (error) {
			console.log('errorNavigate',error);
        };
        
        var get = function () {
			$http.get(url).then(successCallback,errorCallback);
        };

        get();

        var navigateFolders = function () {
            var data = {
                'fileName': $scope.theFile.name,
                'path' : $scope.thePath.path
            };
            $http.post(urlNavigate,data).then(successNavigate,errorNavigate)
        }; 

        $scope.loadFolder = function (file) {
            $scope.theFile = file;
            if (file.folder === true) {
                navigateFolders();
            }
        };

        $scope.parentDirectory = function () {
            if ($scope.thePath.root === false) {
                var data = {
                    'path' : $scope.thePath.path
                };
                $http.post(urlParent,data).then(successNavigate,errorNavigate)
            }
        };

        $scope.save = function() {
            $mdDialog.hide();
        }
        $scope.cancel = function() {
            $mdDialog.cancel();
        }

});

})();
