(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    
    angular.module('common').factory('Config', function($http, $q) {

        var url = 'http://77.81.178.198:25001/onlineShop/';

        return url;

    });

})();
