(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration').controller('loginController', function($scope,loginService) {

        $scope.cb = {
            login : loginService.login
        };

    });

})();
