(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').controller('productController', 
    function($scope,$http,$timeout,$q,$log,$mdDialog,$state,productsService,fileManagerService) {

        productsService.fetchProduct($state.params.id);
        productsService.fetchCategories();
        $scope.cb = {
            getProduct              : productsService.getProduct,
            imageFromManager        : productsService.imageFromManager,
            productImages           : fileManagerService.productImages,
            addNewImage             : productsService.addNewImage,
            removeImage             : productsService.removeImage,
            addProduct              : productsService.addProduct,
            showDialog              : productsService.showDialog,
            getCategories           : productsService.getCategories,
            categoriesArray         : productsService.categoriesArray,
            removeCategoryProduct   : productsService.removeCategoryProduct
        };


        $scope.stocks = [
            {"value" : 'IN_STOCK', "stockStatus" : "In stock"},
            {"value" : 'OUT_OF_STOCK', "stockStatus" : "Out of stock"}
        ];
        
        // if () {

        // }
        // var getProduct = function () {
        //     var urlProduct = '';
        //     $http.get().$promise.then(successCallback,errorcallback);
        // };

        // $scope.sendPost = function(formData) {
        //     var url = 'http://77.81.178.198:25001/onlineShop/products';

        //     $http({
        //       method: 'POST',
        //       url: url,
        //       data: {
        //             "categories": [
        //                 {
        //                     "id": formData.categories.id,
        //                     "name": formData.categories.name
        //                 }
        //             ],
        //             "description": formData.description,
        //             "dimensionH": formData.dimensionH,
        //             "dimensionL": formData.dimensionL,
        //             "dimensionW": formData.dimensionW,
        //             "id": formData.id,
        //             "manufacturer": formData.manufacturer,
        //             "metaDescription": formData.metaDescription,
        //             "metaKeywords": formData.metaKeywords,
        //             "metaTitle": formData.metaTitle,
        //             "model": formData.model,
        //             "name": formData.name,
        //             "price": formData.price,
        //             "quantity": formData.quantity,
        //             "shipping": formData.shipping,
        //             "stockStatus": "OUT_OF_STOCK",
        //             "weight": formData.weight
        //         }
        //     }).then(function successCallback(response) {
        //         console.log(response);
        //       }, function errorCallback(response) {
        //           consle.log(response);
        //       });
        // };

        // var get = function () {
        //     var url = 'http://77.81.178.198:25001/onlineShop/categories';
        //         $http({
        //           method: 'GET',
        //           url: url
        //         }).then(function successCallback(response) {
        //             $scope.desserts = response.data;
        //             console.log($scope.desserts);
        //           }, function errorCallback(response) {
        //             // called asynchronously if an error occurs
        //             // or server returns response with an error status.
        //           });
        // };

        // get();
        // $scope.getMatches = function (text) {
        //     text = text.toLowerCase();
        //     var ret = $scope.desserts.content.filter(function (d) {
        //         return d.name.startsWith(text);
        //     });
        //     return ret;
        // };


    });

})();
