(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').controller('productController', 
    function($scope,$http,$timeout,$q,$log,$mdDialog,$state,productsService) {

        productsService.fetchProduct($state.params.id);
        $scope.cb = {
            getProduct : productsService.getProduct
        };


        var successCallback = function (success) {
            console.log(success);
        };

        var errorCallback = function (error) {
            console.log(error);
        };

        // if () {

        // }
        // var getProduct = function () {
        //     var urlProduct = '';
        //     $http.get().$promise.then(successCallback,errorcallback);
        // };

        $scope.sendPost = function(formData) {
            var url = 'http://77.81.178.198:25001/onlineShop/products';

            $http({
              method: 'POST',
              url: url,
              data: {
                    "categories": [
                        {
                            "id": formData.categories.id,
                            "name": formData.categories.name
                        }
                    ],
                    "description": formData.description,
                    "dimensionH": formData.dimensionH,
                    "dimensionL": formData.dimensionL,
                    "dimensionW": formData.dimensionW,
                    "id": formData.id,
                    "manufacturer": formData.manufacturer,
                    "metaDescription": formData.metaDescription,
                    "metaKeywords": formData.metaKeywords,
                    "metaTitle": formData.metaTitle,
                    "model": formData.model,
                    "name": formData.name,
                    "price": formData.price,
                    "quantity": formData.quantity,
                    "shipping": formData.shipping,
                    "stockStatus": "OUT_OF_STOCK",
                    "weight": formData.weight
                }
            }).then(function successCallback(response) {
                console.log(response);
              }, function errorCallback(response) {
                  consle.log(response);
              });
        };

        var get = function () {
            var url = 'http://77.81.178.198:25001/onlineShop/categories';
                $http({
                  method: 'GET',
                  url: url
                }).then(function successCallback(response) {
                    $scope.desserts = response.data;
                    console.log($scope.desserts);
                  }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.
                  });
        };

        get();
        $scope.getMatches = function (text) {
            text = text.toLowerCase();
            var ret = $scope.desserts.filter(function (d) {
                return d.name.startsWith(text);
            });
            return ret;
        };

        $scope.options = [
            {"val" : 0, "name" : "None"},
            {"val" : 1, "name" : "One"},
            {"val" : 2, "name" : "Two"},
            {"val" : 3, "name" : "Three"},
            {"val" : 4, "name" : "Four"},
            {"val" : 5, "name" : "Five"},
            {"val" : 6, "name" : "Six"}
        ];

        $scope.usersModel = {};

        $scope.showDialog = function(evt, dlg) {
           $mdDialog.show({
               parent: angular.element(document.body),
               targetEvent: evt,
               // manually apply focus to the autocomplete control in the dialog
               // (otherwise, the dialog forces focus to the OK button)
               focusOnOpen: true,
               templateUrl: 'administration/dashboard/templates/file-manager/file-manager.html',
               controller: 'FileManagerController'
           }).then(
           function success (screenData) {
               // hit OK
           },
           function failure () {
               // canceled
           });
        };

    });

})();
