(function(){
    'use strict';

    /**
     * This is a sample factory
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration')
    .factory('fileManager', function($http, $q, Config, Upload) {

        var factory = {};

        factory.fetchFiles = function () {
            var urlFiles = Config + 'fileManager/rootDirectory';            
            return $http.get(urlFiles);

        };

        factory.addFolder = function (newFolder) {
            var urlAddFolder = Config + 'fileManager/createDirectory'
            return $http.post(urlAddFolder,newFolder);
        };

        factory.uploadFiles = function (files) {
            var urlUploadFiles = Config + 'upload/images';

            var upload = Upload.http({
                url: urlUploadFiles,
                data: {
                    files: files
                }
            });
            return upload;
        };

        factory.navigateFolders = function (data) {
            var urlNavigate = Config + 'fileManager/navigateThroughFolder';

            return $http({
                url: urlNavigate,
                method: 'POST',
                data: data
            });

        }; 

        factory.parent = function (path) {
            var urlParent = Config + 'fileManager/parentDirectory';

            return $http({
                url: urlParent,
                method: 'POST',
                data: path
            });
        };

        factory.delete = function (path) {
            var urlDelete = Config + 'fileManager/deleteDirectory';

            return $http({
                url: urlDelete,
                method: 'POST',
                data: path
            });
        };

        factory.upload = function (path) {
            var urlUpload = Config + 'upload/files';

            return $http({
                url: urlUpload,
                method: 'POST'
            });
        };

        //UNIVERSAL ADD IMAGE
        factory.addImage = function (images) {
            var addImageUrl = Config + 'home/banner/';
            return $http.post(addImageUrl,images);
        };

        factory.fetchImages = function () {
            var getImageUrl = Config + 'home/banner/';
            return $http.get(getImageUrl);
        };

        return factory;

    });

})();
