(function(){
    'use strict';

    /**
     * This is a sample factory
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration')
    .factory('fileManager', function($http, $q) {

        var factory = {};

        factory.fetchFiles = function () {
            var urlFiles = 'http://77.81.178.198:25001/onlineShop/fileManager/rootDirectory';
            return $http.get(urlFiles);
        };

        return factory;

    });

})();
