(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home', ['ui.bootstrap', 'ui.utils', 'ui.router', 'ngAnimate', 'restangular']);
    
    angular.module('home').config(function($stateProvider) {

        $stateProvider.state('home', {
            url: '/home',
            templateUrl: 'home/templates/home-template.html',
            controller: 'homeController'
        });
        $stateProvider.state('home.category', {
            url: '/category/:id',
            templateUrl: 'home/category/templates/category.html',
            controller: 'homeCategoryController',
            ncyBreadcrumb: {
                label: 'Home'
            }
        });
        $stateProvider.state('home.product', {
            url: '/product/:id/?params',
            templateUrl: 'home/templates/product.html',
            controller: 'homeProductController',
            ncyBreadcrumb: {
                label: 'Product'
            }
		});

        //OPTIONS
        $stateProvider.state('home.account', {
            url: '/account',
            templateUrl: 'home/options/account/account.html',
            controller: 'accountController'            
		});
        $stateProvider.state('home.favorites', {
            url: '/favorites',
            templateUrl: 'home/options/favorites/favorites.html',
            controller: 'favoritesController'            
		});
        $stateProvider.state('home.cart', {
            url: '/cart',
            templateUrl: 'home/options/cart/cart.html',
            controller: 'cartController'            
		});

    });
    

})();
