(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').factory('homeProductService', function($http, $q, $injector, $uibModal) {

        var factory = {},
            Product = $injector.get('homeProductModel'),
            product = {
                loaded: false,
                fetching: true,
                data: {}
            },
            bigImage = {
                data: {}
            },
            picture = {
                data: {}
            };

        var successCallback = function (success) {
            product.data = success.data;
            console.log(product.data);
        };

        var errorCallback = function (error) {
            console.log(error);
        };

        factory.fetchProduct = function () {
            product.fetching = true;
            Product.fetchProduct().then(successCallback,errorCallback);
        };

        factory.getProduct = function () {
            return product.data;
        };

        factory.getBigImagine = function () {

            // if (thumb === undefined && product.data.images !== undefined) {
            //     return bigImage.data = product.data.images[0].srcBig;
            // } else {
            //     return bigImage.data = thumb;
            // }
            if (product.data.images !== undefined && _.isEmpty(picture.data)) {
                return bigImage.data = product.data.images[0].srcBig;
            } else if (picture) {
                return bigImage.data = picture.data;
            }

            // var splitImage,
            //     joinImage;

            // if (bigImage.data.split !== undefined) {
            //     splitImage = bigImage.data.split('thumbnail.');
            //     joinImage = splitImage.join('');
            //     bigImage.data = joinImage;
            //     return bigImage.data;
            // } else if (product.data.images !== undefined) {
            //     splitImage = product.data.images[0].src.split('thumbnail.');
            //     joinImage = splitImage.join('');
            //     return joinImage;
            // }
        };

        factory.getThumbnails = function () {
            var thumbnails = [];
            _.forEach(product.data.images,function(eachImage){
                thumbnails.push(eachImage);
            });
            return thumbnails;
        };

        factory.hoverThumbnails = function (image) {
            picture.data = image.srcBig;
        };

        factory.openModalImages = function (thumb,bigImage) {
            var modalInstance = $uibModal.open({
                // animation: $ctrl.animationsEnabled,
                ariaLabelledBy: 'modal-title',
                ariaDescribedBy: 'modal-body',
                templateUrl: 'home/product/templates/image-modal.html',
                controller: 'imageModalController',
                size: 'lg',
                resolve: {
                    items: function () {
                        return {
                            thumb: thumb,
                            bigImage: bigImage
                        };
                    }
                }
            });

            modalInstance.result.then(function (selectedItem) {
                // $ctrl.selected = selectedItem;
            }, function () {
                // $log.info('Modal dismissed at: ' + new Date());
            });
        };
        
        factory.init = function () {
            product = {
                loaded: false,
                fetching: true,
                data: {}
            };
            bigImage = {
                data: {}
            };
            picture = {
                data: {}
            };
        };
        
        return factory;
    });

})();
