(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').factory('homeProductService', function($http, $q, $injector, $uibModal) {

        var factory = {},
            Product = $injector.get('homeProductModel'),
            product = {
                loaded: false,
                fetching: true,
                data: {}
            },
            bigImage = {
                data: {}
            };

        var successCallback = function (success) {
            product.data = success.data;
            console.log(product.data);
        };

        var errorCallback = function (error) {
            console.log(error);
        };

        factory.fetchProduct = function () {
            product.fetching = true;
            Product.fetchProduct().then(successCallback,errorCallback);
        };

        factory.getProduct = function () {
            return product.data;
        };

        factory.getThumbnails = function () {
            var thumbnails = [];
            _.forEach(product.data.images,function(eachImage){
                // var splitImage = eachImage.src.split('thumbnail.');
                // var joinImage = splitImage.join('');
                // $scope.hoveredImage = $scope.bigImage[0];
                // $scope.allImages = $scope.bigImage;
                thumbnails.push(eachImage.src);
            });
            return thumbnails;
        };

        factory.hoverThumbnails = function (image) {
            bigImage.data = image;
        };

        factory.getBigImagine = function () {
            var splitImage,
                joinImage;

            if (bigImage.data.split !== undefined) {
                splitImage = bigImage.data.split('thumbnail.');
                joinImage = splitImage.join('');
                bigImage.data = joinImage;
                return bigImage.data;
            } else if (product.data.images !== undefined) {
                splitImage = product.data.images[0].src.split('thumbnail.');
                joinImage = splitImage.join('');
                return joinImage;
            }
        };

        factory.openModalImages = function (thumb) {
            var modalInstance = $uibModal.open({
                // animation: $ctrl.animationsEnabled,
                ariaLabelledBy: 'modal-title',
                ariaDescribedBy: 'modal-body',
                templateUrl: 'home/product/templates/image-modal.html',
                controller: 'imageModalController',
                size: 'lg',
                resolve: {
                    items: function () {
                        return {
                            thumb: thumb,
                            bigImage: product.data.images
                        };
                    }
                }
            });

            modalInstance.result.then(function (selectedItem) {
                // $ctrl.selected = selectedItem;
            }, function () {
                // $log.info('Modal dismissed at: ' + new Date());
            });
        };
        
        factory.init = function () {
            product = {
                loaded: false,
                fetching: true,
                data: {}
            };
            bigImage = {
                data: {}
            };
        };
        
        return factory;
    });

})();
