(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home').factory('homeProductModel', function($http, $q, $stateParams, Config) {

        var factory = {};

        // factory.fetchProduct = function () {
        //     var url = Config + 'products/' + $stateParams.id;
        //     return $http.get(url);
        // };
        factory.fetchProduct = function (id) {
            var url = Config + 'products/' + id;
            return $http.get(url);
        };

        return factory;
    });

})();
