(function(){
    'use strict';

    /**
     * This is the main application file.
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('storeApp', ['ui.bootstrap', 'ui.utils', 'ui.router', 'ngAnimate', 'restangular', 'angular-loading-bar', 'home', 'common', 'administration', 'ngMaterial', 'ncy-angular-breadcrumb', 'md.data.table', 'rzModule', 'ngFileUpload', 'ngCookies', 'ui-notification']);
    
    angular.module('storeApp').config(function($stateProvider, $urlRouterProvider, $httpProvider) {

        /* Add New States Above */
        $urlRouterProvider.otherwise('/login');
        // console.log('$httpProvider',$httpProvider);
        
        $httpProvider.defaults.withCredentials = true;

    });
    
    angular.module('storeApp').run(function($rootScope, $state, $location, HttpErrors) {
        $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {


        //     // console.log(event, toState, toParams, fromState, fromParams);

        //     if (loginService.getAuthStatus()) {
        //         $location.path('/administration');
        //     } else {
        //         $location.path('/login');
        //     }
        //     // if (toState.authentificated) {
        //     //     if (!loginService.getAuthStatus()) {
        //     //         console.log(toState.authentificated);
        //     //         $location.path('/administration');
        //     //     }
        //     // }

        //     // if (toState.url === '/') {
        //     //     if (loginService.getAuthStatus()) {
        //     //         // $state.go('toState.url');
        //     //         console.log(toState.url);
        //     //         $location.path(toState.url);
        //     //     }
        //     // }
        //     // var isAuthenticationRequired =  toState.data && toState.data.requiresLogin && !PsAuthUserService.isLoggedIn;
        //     // if(isAuthenticationRequired) {
        //     //     event.preventDefault();
        //     //     $state.go('auth.login');
        //     // }
        });

        $rootScope.safeApply = function(fn) {
            var phase = $rootScope.$$phase;
            if (phase === '$apply' || phase === '$digest') {
                if (fn && (typeof(fn) === 'function')) {
                    fn();
                }
            } else {
                this.$apply(fn);
            }
        };

        
    });

})();
