(function(){
    'use strict';

    /**
     * This is a sample service spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('categoriesModel', function() {

        var service;

        beforeEach(function(){
            module('administration');

            inject(function(categoriesModel){
                service = categoriesModel;
            });
        });

        it('should ...', function() {

            //TODO: Implement your service spec logic here
            //expect(service.doSomething()).toEqual('something');

        });

    });

})();
