(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').controller('productsCtrl', function($scope, $http, productsService) {

        productsService.fetchProducts();
        $scope.cb = {
            getProducts       : productsService.getProducts,
            getTotalElements  : productsService.getTotalElements,
            getTotalPages     : productsService.getTotalPages
        };
        
        $scope.selected = [];

        $scope.query = {
            limit: 10,
            page: 1
        };

        $scope.getPage = function () {
            productsService.pagination($scope.query);
        };

    });

})();
