(function(){
    'use strict';

    /**
     * This is a sample controller spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('favoritesController', function() {

        var scope, ctrl;

        beforeEach(function() {
            module('home');

            inject(function($rootScope, $controller) {
                scope = $rootScope.$new();
                ctrl = $controller('favoritesController', {$scope: scope});
            });
        });

        it('should ...', function() {

            //TODO: Implement your controller spec logic here
            //expect(ctrl.doSomething()).toEqual('something');

        });

    });

})();
