(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('home').factory('homeCategoryService', function($http, $q, $injector, $state) {

        var factory = {},
            Categories = $injector.get('homeCategoryModel'),
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            };

        var successCallback = function (success) {
            categories.data = success.data.content;
        };

        var errorCallback = function (error) {
            console.log(error);
        };

        factory.fetchCategories = function (id) {
            categories.fetching = true;
            Categories.fetchCategories(id).then(successCallback,errorCallback);
        };

        factory.getProducts = function () {
            return categories.data;
        };

        factory.getProduct = function (product) {
            var data = product.name.split(' ').join('-');
            $state.go('home.product',{id: product.id,params: data});
        };

        factory.init = function () {
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            };
        };

        return factory;

    });

})();
