(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('home').factory('homeCategoryModel', function($http, $q, Config) {

        var factory = {};

        factory.fetchCategories = function (id) {
            var getCategoryUrl = Config +  'products/categories/' + id;
            return $http.get(getCategoryUrl);
        };

        return factory;

    });

})();
