(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home').factory('homeModel', function($http, $q, Config) {

        var factory = {};

        factory.fetchNavigation = function () {
            var urlNavigation = Config + 'home/navigation';
            return $http.get(urlNavigation);
        };

        return factory;
    });

})();
