(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').factory('homeService', function($http, $q, $injector) {
        
        var factory = {},
            Navigator = $injector.get('homeModel'),
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            };

        var successCallback = function (success) {
            categories.data = success.data;
        };

        var errorCallback = function (error) {
            console.log(error);
        };

        factory.fetchNavigation = function () {
            categories.fetching = true;
            Navigator.fetchNavigation().then(successCallback,errorCallback);
        };

        factory.getNavigation = function () {
            return categories.data;
        };

        factory.init = function () {
            categories = {
                loaded: false,
                fetching: true,
                data: {}
            };
        };

        return factory;

    });

})();
