(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').controller('bannerController', function($scope, fileManagerService) {

        fileManagerService.fetchImages();
        $scope.cb = {
            addNewImage   : fileManagerService.addNewImage,
            selectedImage : fileManagerService.selectedImage,
            showDialog    : fileManagerService.showDialog,
            addImage      : fileManagerService.addImage,
            getImage      : fileManagerService.getImage
        };

    });

})();
