(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home').controller('homeCategoryController', function($scope, $http, $stateParams) {

        var getCategoryUrl = 'http://77.81.178.198:25001/onlineShop/products/categories/' + $stateParams.id;
        $http.get(getCategoryUrl).then(function(success){
            console.log('success',success.data.content);
            $scope.products = success.data.content;
        });
            
        //Range slider config
        $scope.minRangeSlider = {
            minValue: 10,
            maxValue: 90,
            options: {
                floor: 0,
                ceil: 100,
                step: 1
            }
        };

    });

})();
