(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('home').controller('homeCategoryController', function($scope, $http, $state, $stateParams, Config, homeCategoryService) {

        homeCategoryService.fetchCategories($stateParams.id);
        $scope.cb = {
            getProducts : homeCategoryService.getProducts,
            getProduct  : homeCategoryService.getProduct
        };
            
        //Range slider config
        $scope.minRangeSlider = {
            minValue: 10,
            maxValue: 90,
            options: {
                floor: 0,
                ceil: 100,
                step: 1
            }
        };

    });

})();
