(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('home').controller('homeCategoryController', function($scope, $http, $state, $stateParams, Config) {

        var getCategoryUrl = Config +  'products/categories/' + $stateParams.id;
        $http.get(getCategoryUrl).then(function(success){
            $scope.products = success.data.content;
        });

        $scope.getProduct = function (product) {
            console.log(product);
            $state.go('home.product',{id: product.id});
        };
            
        //Range slider config
        $scope.minRangeSlider = {
            minValue: 10,
            maxValue: 90,
            options: {
                floor: 0,
                ceil: 100,
                step: 1
            }
        };

    });

})();
