(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').controller('homeController', 
    function($scope, $http, $state, $rootScope, Config, homeService, fileManagerService) {

        homeService.fetchNavigation();
        fileManagerService.fetchImages();
        $scope.cb = {
            getNavigation : homeService.getNavigation,
            getImage      : fileManagerService.getImage
        };

        $scope.$state = $state;
        if ($state.current.name === 'home') {
            $scope.isHome = true;
        }

        $rootScope.$on('$stateChangeStart',function (event, toState, toParams, fromState, fromParams) { 
            if (toState.name !== 'home') {
                $scope.isHome = false;
            } else {
                $scope.isHome = true;
            }
        });

        $scope.account = {
            templateUrl: 'home/options/account/account.html',
        };
        $scope.favorites = {
            templateUrl: 'home/options/favorites/favorites.html',
        };
        $scope.cart = {
            templateUrl: 'home/options/cart/cart.html',
        };

        $scope.myInterval = 3000;
        $scope.noWrapSlides = false;
        $scope.slides = [
            {
            image: 'http://lorempixel.com/400/200/'
            },
            {
            image: 'http://lorempixel.com/400/200/food'
            },
            {
            image: 'http://lorempixel.com/400/200/sports'
            },
            {
            image: 'http://lorempixel.com/400/200/people'
            }
        ];
        

    });

})();
