(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').factory('Products', function($http, $q, $state, Config) {

        var factory = {};
        
        factory.fetchProducts = function (query) {
            var urlProducts = Config +  'products?page=' + (query.page - 1) + '&size=' + query.limit;
            return $http.get(urlProducts);
        };

        factory.fetchProduct = function (id) {
            var urlProduct = Config + 'products/' + id;
            return $http.get(urlProduct);
        };

        factory.addProduct = function (formData) {
            var addProductUrl;

            if ($state.params.id) {
                addProductUrl = Config + 'products/' + $state.params.id;
                return $http.put(addProductUrl,formData);
            } else {
                addProductUrl = Config + 'products';
                return $http.post(addProductUrl,formData);
            }

        };

        factory.fetchCategories = function () {
            var categoriesUrl = Config + 'categories';
            return $http.get(categoriesUrl);
        };

        return factory;

    });

})();
