(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').factory('Products', function($http, $q) {

        var factory = {};
        
        factory.fetchProducts = function (query) {
            var urlProducts = 'http://77.81.178.198:25001/onlineShop/products?page=' + (query.page - 1) + '&size=' + query.limit;
            return $http.get(urlProducts);
        };

        return factory;

    });

})();
