(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').factory('productsService', function($http, $q, $injector) {

        var factory = {},
            Products = $injector.get('Products'),
            products = {
                loaded: false,
                fetching: true,
                data: {}
            },
            query = {
                order: 'name',
                limit: 5,
                page: 1
            };

        var successCallback = function (success) {
            console.log(success.data);
            products.data = success.data;
        };

        var errorCallback = function (error) {
            console.log(error);
        };
        
        factory.getProducts = function () {
            return products.data.content;
        };

        factory.getPagination = function () {
            return products.data.content;
        };

        factory.pagination = function (query) {
            if (query !== undefined) {
                products.fetching = true;
                Products.fetchProducts(query).then(successCallback,errorCallback);
            }
            // console.log(query);
            // query.limit = query.limit;
            // query.page = query.page;
            // return factory.getProducts();
            // return;
        };

        factory.fetchProducts = function () {
            products.fetching = true;
            Products.fetchProducts(query).then(successCallback,errorCallback);
        };

        factory.init = function (newMode) {
            products = {
                loaded: false,
                fetching: true,
                data: {}
            };
            query = {
                order: 'name',
                limit: 5,
                page: 1
            };
        };
        
        return factory;

    });

})();
