(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').factory('productsService', function($http, $q, $injector) {

        var factory = {},
            Products = $injector.get('Products'),
            products = {
                loaded: false,
                fetching: true,
                data: {}
            },
            product = {
                loaded: false,
                fetching: true,
                data: {}
            },
            image = {
                loaded: false,
                fetching: true,
                data: {}
            },
            query = {
                order: 'name',
                limit: 10,
                page: 1
            };

        var successCallback = function (success) {
            console.log(success.data);
            products.data = success.data;
            product.data = success.data;
        };

        var errorCallback = function (error) {
            console.log(error);
        };
        
        factory.getProducts = function () {
            return products.data.content;
        };

        factory.getProduct = function () {
            return product.data;
        };

        factory.getTotalElements = function () {
            return products.data.totalElements;
        };

        factory.getTotalPages = function () {
            return products.data.totalPages;
        };

        factory.pagination = function (query) {
            if (query !== undefined) {
                products.fetching = true;
                Products.fetchProducts(query).then(successCallback,errorCallback);
            }
        };

        factory.fetchProducts = function () {
            products.fetching = true;
            Products.fetchProducts(query).then(successCallback,errorCallback);
        };

        factory.fetchProduct = function (id) {
            product.fetching = true;
            Products.fetchProduct(id).then(successCallback,errorCallback);
        };

        factory.imageProduct = function (image) {
            // image.data.push(images);
            image.data = image;
        };

        factory.imageFromManager = function () {
            return image.data;
        }

        factory.init = function (newMode) {
            products = {
                loaded: false,
                fetching: true,
                data: {}
            };
            product = {
                loaded: false,
                fetching: true,
                data: {}
            };
            image = {
                loaded: false,
                fetching: true,
                data: {}
            };
            query = {
                order: 'name',
                limit: 5,
                page: 1
            };
        };
        
        return factory;

    });

})();
