(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').factory('Products', function($http, $q, $state) {

        var factory = {};
        
        factory.fetchProducts = function (query) {
            var urlProducts = 'http://77.81.178.198:25001/onlineShop/products?page=' + (query.page - 1) + '&size=' + query.limit;
            return $http.get(urlProducts);
        };

        factory.fetchProduct = function (id) {
            var urlProduct = 'http://77.81.178.198:25001/onlineShop/products/' + id;
            return $http.get(urlProduct);
        };

        factory.addProduct = function (formData) {
            var addProductUrl;

            if ($state.params.id) {
                addProductUrl = 'http://77.81.178.198:25001/onlineShop/products/' + $state.params.id;
                return $http.put(addProductUrl,formData);
            } else {
                addProductUrl = 'http://77.81.178.198:25001/onlineShop/products';
                return $http.post(addProductUrl,formData);
            }

        };

        return factory;

    });

})();
