(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration', ['ui.bootstrap', 'ui.utils', 'ui.router', 'ngAnimate', 'restangular']);
    
    angular.module('administration').config(function($stateProvider) {

        // Category route
        $stateProvider.state('dashboard.categories', {
            url: '/categories',
            templateUrl: 'administration/dashboard/templates/categories/categories.html',
            controller: 'categoriesCtrl',
            ncyBreadcrumb: {
                label: 'Categories'
            }
        });
        //Add Category route
        $stateProvider.state('dashboard.add-category', {
            url: '/category/add',
            templateUrl: 'administration/dashboard/templates/add-category/add-category.html',
            controller: 'addCategoryCtrl',
            ncyBreadcrumb: {
                label: 'Categories / Add Category'
                // parent: 'categories'
            }
        });
        
        // Products route
        $stateProvider.state('dashboard.products', {
            url: '/products',
            templateUrl: 'administration/dashboard/templates/products/products.html',
            controller: 'productsCtrl',
            ncyBreadcrumb: {
                label: 'Products'
            },
            // ncyBreadcrumbLabel: '<i class="fa fa-rocket logo-icon" aria-hidden="true"></i>'
           
		});
        //Add Product route
        $stateProvider.state('dashboard.add-product', {
            url: '/product/add',
            templateUrl: 'administration/dashboard/templates/add-product/add-product.html',
            controller: 'addProductCtrl',
            ncyBreadcrumb: {
                label: 'Products / Add Product'
                // parent: 'products'
            }
        });

        $stateProvider.state('dashboard.file-manager', {
            url: '/file-manager',
            templateUrl: 'administration/dashboard/templates/file-manager/file-manager.html',
            controller: 'FileManagerController',
            ncyBreadcrumb: {
                label: 'Products / Add Product'
                // parent: 'products'
            }
		});

    });
    

})();
