(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('administration', ['ui.bootstrap', 'ui.utils', 'ui.router', 'ngAnimate', 'restangular']);
    
    angular.module('administration').config(function($stateProvider) {

        // Category route
        $stateProvider
        .state('dashboard.categories', {
            url: '/categories',
            templateUrl: 'administration/dashboard/templates/categories/categories.html',
            controller: 'categoriesController',
            ncyBreadcrumb: {
                label: 'Categories'
            }
        })
        //Add Category route
        .state('dashboard.category', {
            url: '/category/:id',
            templateUrl: 'administration/dashboard/templates/category/category.html',
            controller: 'categoryController',
            ncyBreadcrumb: {
                label: 'Categories / Category'
                // parent: 'categories'
            }
        })
        
        // Products route
        .state('dashboard.products', {
            url: '/products',
            templateUrl: 'administration/dashboard/templates/products/products.html',
            controller: 'productsCtrl',
            ncyBreadcrumb: {
                label: 'Products'
            },
            // ncyBreadcrumbLabel: '<i class="fa fa-rocket logo-icon" aria-hidden="true"></i>'
           
		})
        //Add Product route
        .state('dashboard.product', {
            url: '/product/:id',
            templateUrl: 'administration/dashboard/templates/product/product.html',
            controller: 'productController',
            ncyBreadcrumb: {
                label: 'Products / Product'
                // parent: 'products'
            }
        })

        .state('dashboard.file-manager', {
            url: '/file-manager',
            templateUrl: 'administration/dashboard/templates/file-manager/file-manager.html',
            controller: 'FileManagerController'
		});

    });
    

})();
