(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration', ['ui.bootstrap', 'ui.utils', 'ui.router', 'ngAnimate', 'restangular']);
    
    angular.module('administration').config(function($stateProvider) {

        $stateProvider.state('login', {
            url: '/login',
            templateUrl: 'administration/authentification/templates/login/login.html',
            controller: 'loginController'
            // ncyBreadcrumb: {
            //     label: 'Home'
            // }
        });
        
        $stateProvider.state('dashboard', {
            url: '/administration',
            templateUrl: 'administration/dashboard/templates/dash/dashboard.html',
            controller: 'dashCtrl',
            authentificated: true,
            ncyBreadcrumb: {
                label: 'Home'
            }
        });
        
        // Category route
        $stateProvider
        .state('dashboard.categories', {
            url: '/categories',
            templateUrl: 'administration/dashboard/templates/categories/categories.html',
            controller: 'categoriesController',
            authentificated: true,
            ncyBreadcrumb: {
                label: 'Categories'
            }
        })
        //Add Category route
        .state('dashboard.category', {
            url: '/category/:id',
            templateUrl: 'administration/dashboard/templates/category/category.html',
            controller: 'categoryController',
            authentificated: true,
            ncyBreadcrumb: {
                label: 'Categories / Category'
                // parent: 'categories'
            }
        })
        
        // Products route
        .state('dashboard.products', {
            url: '/products',
            templateUrl: 'administration/dashboard/templates/products/products.html',
            controller: 'productsCtrl',
            authentificated: true,
            ncyBreadcrumb: {
                label: 'Products'
            },
            // ncyBreadcrumbLabel: '<i class="fa fa-rocket logo-icon" aria-hidden="true"></i>'
           
		})
        //Add Product route
        .state('dashboard.product', {
            url: '/product/:id',
            templateUrl: 'administration/dashboard/templates/product/product.html',
            controller: 'productController',
            authentificated: true,
            ncyBreadcrumb: {
                label: 'Products / Product'
                // parent: 'products'
            }
        })

        .state('dashboard.file-manager', {
            url: '/file-manager',
            templateUrl: 'administration/dashboard/templates/file-manager/file-manager.html',
            controller: 'FileManagerController',
            authentificated: true
		})
        
        //MODULES
        .state('dashboard.modules', {
            url: '/modules',
            templateUrl: 'administration/dashboard/templates/modules/modules.html',
            controller: 'modulesController',
            authentificated: true
		})
        //Banner
        .state('dashboard.banner', {
            url: '/banner',
            templateUrl: 'administration/dashboard/templates/modules/banner/banner.html',
            controller: 'bannerController',
            authentificated: true
		});

    })

    .run(function($rootScope, $state, $location, authService) {
        $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
            console.log(event, toState, toParams, fromState, fromParams);

            if (authService.isLoggedIn()) {
                $location.path('/administration');
            } else {
                $location.path('/login');
            }
            // if (toState.authentificated) {
            //     if (!loginService.getAuthStatus()) {
            //         console.log(toState.authentificated);
            //         $location.path('/administration');
            //     }
            // }

            // if (toState.url === '/') {
            //     if (loginService.getAuthStatus()) {
            //         // $state.go('toState.url');
            //         console.log(toState.url);
            //         $location.path(toState.url);
            //     }
            // }
            // var isAuthenticationRequired =  toState.data && toState.data.requiresLogin && !PsAuthUserService.isLoggedIn;
            // if(isAuthenticationRequired) {
            //     event.preventDefault();
            //     $state.go('auth.login');
            // }
        });
        
    });
    

})();
