(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('administration').controller('categoryController', function($scope,$http,$timeout,$q,$log,$state,categoriesService) {

        categoriesService.fetchCategory($state.params.id);
        $scope.cb = {
            getCategory   : categoriesService.getCategory,
            getCategories : categoriesService.getCategories
        };
        
        
        // $scope.sendPost = function(formData) {
        //     var url = 'http://77.81.178.198:25001/onlineShop/categories';

        //     $http({
        //       method: 'POST',
        //       url: url,
        //       data: {
        //         'description': formData.description,
        //         'metaDescription': formData.metaDescription,
        //         'metaKeywords': formData.metaKeywords,
        //         'metaTitle': formData.metaTitle,
        //         'name': formData.name,
        //         'parentCategoryId': formData.parentCategoryId ? formData.parentCategoryId.id : null
        //       }
        //     }).then(function successCallback(response) {
        //         console.log(response);
        //       }, function errorCallback(response) {
        //         // called asynchronously if an error occurs
        //         // or server returns response with an error status.
        //       });
        // };

        var get = function () {
            var url = 'http://77.81.178.198:25001/onlineShop/categories';
                $http({
                  method: 'GET',
                  url: url
                }).then(function successCallback(response) {
                    $scope.desserts = response.data;
                    console.log($scope.desserts);
                  }, function errorCallback(response) {
                    // called asynchronously if an error occurs
                    // or server returns response with an error status.
                  });
        };

        get();

        $scope.getMatches = function (text) {
            text = text.toLowerCase();
            var ret = $scope.desserts.filter(function (d) {
                return d.name.startsWith(text);
            });
            return ret;
        };
    });

})();
