(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home').controller('homeProductController', function($scope, $http, $stateParams, Config) {

        console.log($stateParams);
        var getProductPage = function () {
            var url = Config + 'products/' + $stateParams.id;
            $http.get(url);
        };
        getProductPage();

    });

})();
