(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').controller('imageModalController', function($scope,items) {

        console.log('items',items);
        $scope.image = items;

        $scope.click = function (thumb) {
            console.log(thumb);
            $scope.image.thumb = thumb;
        };

    });

})();
