(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */
    angular.module('home').controller('imageModalController', function($scope,items) {

        console.log('items',items);
        $scope.image = items;

        $scope.click = function (thumb) {
            console.log(thumb);
            $scope.image.thumb = thumb;
        };

        $scope.showCreateNewInterfacePanel=true;

    });

    // .directive('ngMouseWheelUp', function() {
    //     return function(scope, element, attrs) {
    //         element.bind("DOMMouseScroll mousewheel onmousewheel", function(event) {
                   
    //         	        // cross-browser wheel delta
    //         	        var event = window.event || event; // old IE support
    //         	        var delta = Math.max(-1, Math.min(1, (event.wheelDelta || -event.detail)));
            	
    //         	        if(delta > 0) {
    //                         scope.$apply(function(){
    //                             scope.$eval(attrs.ngMouseWheelUp);
    //                         });
                        
    //                       // for IE
    //                       event.returnValue = false;
    //                       // for Chrome and Firefox
    //                       if(event.preventDefault) event.preventDefault();                        
    //                    }
    //             });
    //         };
    // })


    // .directive('ngMouseWheelDown', function() {
    //         return function(scope, element, attrs) {
    //             element.bind("DOMMouseScroll mousewheel onmousewheel", function(event) {
                    
    //                         // cross-browser wheel delta
    //                         var event = window.event || event; // old IE support
    //                         var delta = Math.max(-1, Math.min(1, (event.wheelDelta || -event.detail)));
                    
    //                         if(delta < 0) {
    //                             scope.$apply(function(){
    //                                 scope.$eval(attrs.ngMouseWheelDown);
    //                             });

    //                         // for IE
    //                         event.returnValue = false;
    //                         // for Chrome and Firefox
    //                         if(event.preventDefault) event.preventDefault();                        
    //                     }
    //             });
    //         };
    // });

})();
