(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration').factory('loginModel', function($http, $q, Config) {

        var factory = {};

        factory.login = function (credentials) {
            var loginUrl = Config + 'administrator/login?username=' + credentials.username + '&password=' + credentials.password ;
            return $http.post(loginUrl);
        };

        return factory;

    });

})();
