(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration').factory('loginService', function($http, $q, $injector, $state) {

        var factory = {},
            Login = $injector.get('loginModel');

        var successLogin = function (success) {
            console.log(success);
        };

        var errorLogin = function (error) {
            console.log(error);
        };

        factory.login = function (credentials) {
            Login.login(credentials).then(successLogin,errorLogin);
            $state.go('dashboard');
        };

        return factory;

    });

})();
