(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration')
    .factory('authService', function($http, $q, $injector, $state, $cookies) {

        var Login = $injector.get('authModel'),
        
        errorCallback = function (error) {
            console.log(error);
        };

        return {
            // authorize: function(accessLevel, role) {
            //     var status = $cookies.get('auth');
            //     console.log('status', status);

            //     if (status) {
            //         return true;
            //     } else {
            //         return false;
            //     }

            // // if(role === undefined)
            // //     role = $rootScope.user.role;
            // //     return accessLevel &amp; role;
            // },

            isLoggedIn: function(user) {
                var status = $cookies.get('auth');
                console.log('status', status);
                
                if (status) {
                    return true;
                } else {
                    return false;
                }

                // if(user === undefined)
                //     user = $rootScope.user;
                // return user.role === userRoles.user || user.role === userRoles.admin;
            },

            // register: function(user, success, error) {
            //     $http.post('/register', user).success(success).error(error);
            // },

            login: function(credentials, success, error) {
                Login.login(credentials).then(function(success){
                    $cookies.put('auth', 'authentificated');
                    $state.go('dashboard');
                },errorCallback);
            },

            // logout: function(success, error) {
            //     $http.post('/logout').success(function(){
            //         $rootScope.user = {
            //             username = '',
            //             role = userRoles.public
            //         };
            //         success();
            //     }).error(error);
            // }
        };

        // var factory = {},
        //     Login = $injector.get('authModel');

        // var successLogin = function (success) {
        //     console.log(success);
        //     $cookies.put('auth', 'authentificated');
        //     $state.go('dashboard');
        // };

        // var errorLogin = function (error) {
        //     console.log('error',error);
        //     // if (error.error === ) {

        //     // }
        // };

        // factory.login = function (credentials) {
        //     Login.login(credentials).then(successLogin,errorLogin);
        // };

        // factory.getAuthStatus = function () {
        //     var status = $cookies.get('auth');
        //     console.log('status',status);
        //     if (status) {
        //         return true;
        //     } else {
        //         return false;
        //     }
        // };

        // return factory;

    });

})();
