(function () {
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration').factory('authModel', function ($http, $q, Config) {

        var factory = {};

        factory.login = function (credentials) {

            var loginUrl = Config + 'api/auth/login';

            return $http.post(loginUrl, {
                username: credentials.username,
                password: credentials.password
            }, {
                    headers: {
                        'Content-Type': 'application/json',
                        'Cache-Control': 'no-cache',
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                }

            );

        };


        // factory.login = function (credentials) {
        //     var loginUrl = Config + 'administrator/login?username=' + credentials.username + '&password=' + credentials.password ;
        //     $http.post(loginUrl, credentials, {
        //         withCredentials: true
        //     });
        // };

        return factory;

    });

})();
