(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Achim Dan
     */

    angular.module('administration').factory('authModel', function($http, $q, Config) {

        var factory = {};

        factory.login = function (credentials) {
            var loginUrl = Config + 'administrator/login?username=' + credentials.username + '&password=' + credentials.password ;
            return $http.post(loginUrl);
        };


        // factory.login = function (credentials) {
        //     var loginUrl = Config + 'administrator/login?username=' + credentials.username + '&password=' + credentials.password ;
        //     $http.post(loginUrl, credentials, {
        //         withCredentials: true
        //     });
        // };

        return factory;

    });

})();
